plugins:
  - import
  - react
  - prettier
  - react-hooks
  - jsx-a11y

env:
  browser: true
  es6: true
  jest: true
  node: true
  
settings:
  react:
    version: detect

parser: 'babel-eslint'
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react-hooks/recommended'

parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true

rules:
  # Quality Rules - JS

  array-callback-return: error
  camelcase: off
  dot-notation:
    - error
    - allowPattern: '^[a-z]+(_[a-z]+)+$'
  eqeqeq: error
  max-params:
    - error
    - max: 6
  max-statements:
    - error
    - max: 15
  max-statements-per-line:
    - warn
    - max: 3
  no-alert: error
  no-case-declarations: error
  no-class-assign: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-console: error
  no-constant-condition: error
  no-const-assign: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-else-return: error
  no-empty: error
  no-empty-character-class: error
  no-empty-pattern: error
  no-undef: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true
      allowTaggedTemplates: true
  no-unused-vars:
    - error
    - args: all
      argsIgnorePattern: '^_'
      vars: all
      varsIgnorePattern: '^_'
  no-useless-return: error
  no-var: error
  prefer-const: error
  prefer-destructuring: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  yoda: error

  # Quality Rules - Import

  import/default: error
  import/export: error
  import/named: error
  import/namespace: error
  import/no-duplicates: error
  import/no-named-as-default: error
  import/no-named-as-default-member: error
  import/prefer-default-export: off

  # Quality Rules - React

  react/jsx-key: error
  react/jsx-no-comment-textnodes: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-target-blank: error
  react/jsx-no-undef: error
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/no-children-prop: error
  react/no-danger-with-children: error
  react/no-deprecated: error
  react/no-direct-mutation-state: error
  react/no-render-return-value: error
  react/no-string-refs: error
  react/no-unescaped-entities: error
  react/no-unknown-property: error
  react/prop-types: error

  # Stylistic Rules - These Rules will be replaced by Prettier soon

  arrow-spacing: warn
  dot-location:
    - warn
    - property
  max-len:
    - warn
    - 130
    - ignoreUrls: true
  no-extra-semi: warn
  no-mixed-spaces-and-tabs: warn
  no-multiple-empty-lines:
    - warn
    - max: 1
  quotes:
    - warn
    - single
  rest-spread-spacing: warn
  semi:
    - warn
    - always

  jsx-a11y/anchor-is-valid: warn
