export const FETCH_CONFIG = 'FETCH_CONFIG';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_CONTENT = 'FETCH_CONTENT';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAILED = 'FETCH_CONTENT_FAILED';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';
export const FETCH_POSTS_DETAILS = 'FETCH_POSTS_DETAILS';
export const FETCH_POSTS_DETAILS_SUCCESS = 'FETCH_POSTS_DETAILS_SUCCESS';
export const FETCH_POSTS_DETAILS_FAILED = 'FETCH_POSTS_DETAILS_FAILED';
//redirect
export const REDIRECT_SCREEN = 'REDIRECT_SCREEN';
